version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: twilio
    versions:
    - 6.53.0
    - 6.54.0
    - 6.55.0
    - 6.56.0
  - dependency-name: pyflakes
    versions:
    - 2.3.0
  - dependency-name: flake8
    versions:
    - 3.9.0
  - dependency-name: prompt-toolkit
    versions:
    - 3.0.16
    - 3.0.17
  - dependency-name: alembic
    versions:
    - 1.5.2
    - 1.5.3
    - 1.5.4
    - 1.5.5
    - 1.5.6
    - 1.5.7
  - dependency-name: arrow
    versions:
    - 1.0.3
  - dependency-name: httplib2
    versions:
    - 0.18.0
    - 0.19.0
  - dependency-name: pytz
    versions:
    - "2020.5"
    - "2021.1"
  - dependency-name: sqlalchemy
    versions:
    - 1.3.22
    - 1.3.23
  - dependency-name: pytest-cov
    versions:
    - 2.11.1
  - dependency-name: pytest-pythonpath
    versions:
    - 0.7.3
  - dependency-name: flask
    versions:
    - "1.0"
  - dependency-name: mock
    versions:
    - 4.0.3
  - dependency-name: werkzeug
    versions:
    - 0.15.3
  - dependency-name: jinja2
    versions:
    - 2.10.1
